name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'New Features'
    labels:
      - 'feat'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Maintenance'
    labels:
      - 'ci'
      - 'chore'
      - 'perf'
      - 'refactor'
      - 'test'
  - title: 'Documentation'
    label: 'docs'
  - title: 'Dependency Upgrades'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'patch'
  default: patch

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'ci'
    branch:
      - '/ci\/.+/'
  - label: 'dependencies'
    branch:
      - '/dependencies\/.+/'
  - label: 'docs'
    branch:
      - '/docs\/.+/'
  - label: 'feature'
    branch:
      - '/feat(ure)?\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'perf'
    branch:
      - '/perf\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
  - label: 'security'
    branch:
      - '/security\/.+/'
  - label: 'test'
    branch:
      - '/test\/.+/'
